### ISSUE TITLE
Generated config prevents CloudCannon's handling of Jekyll tags

### ISSUE THREAD

**Issue by rycoll** [CloudCannon/cloudcannon-config-migrator#1]
I ran the migrator over a Jekyll site, and it produced the following config:

```
collections_config:
  posts:
    schemas:
      default:
        _inputs:
	  $.tags:
	    type: multiselect
	    options:
	      values: [] # I assume this line is the problem
	      allow_create: true
	      allow_empty: true
```

This worked great! 

... except that when I clicked the `tags` multiselect for posts in the Content Editor, I didn't get a dropdown showing all the existing tags on the site, which is normally what CloudCannon does for `tags` on a Jekyll post. Commenting out the `_inputs.$.tags` config allowed this behaviour to start working again.

Perhaps the migrator could avoid overwriting the default behaviour for `tags` on a Jekyll site?
